#!/usr/bin/env python3

import sys
import time
from sympy import isprime, nextprime, factorint

def find_prime_factors(n):
    if isprime(n):
        return [n]
    factors = factorint(n)
    return sorted(factors.keys())

def main(file_path):
    with open(file_path, 'r') as file:
        n = int(file.readline().strip())
        start_time = time.time()
        prime_factors = find_prime_factors(n)
        end_time = time.time()

        for factor in prime_factors:
            print(factor)

        print("Time taken:", end_time - start_time, "seconds")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python factorize_rsa.py rsa")
        sys.exit(1)

    file_path = sys.argv[1]
    main(file_path)
